---
services:
  factorio-server-manager:
    image: ofsm/ofsm:latest
    container_name: factorio-server-manager
    pull_policy: always
    environment:
      - "FACTORIO_VERSION=stable"
      - "RCON_PASS"
    volumes:
      - ${APPDATA_PATH}/saves:/opt/factorio/saves
      - ${APPDATA_PATH}/mods:/opt/factorio/mods
      - ${APPDATA_PATH}/config:/opt/factorio/config
      - ${APPDATA_PATH}/mod_packs:/opt/fsm/mod_packs
    ports:
      - "8888:80"
      - "34197:34197/udp"
    restart: "unless-stopped"
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    pull_policy: always
    restart: unless-stopped
    command: agent
    environment:
      - DOZZLE_HOSTNAME=factorio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
