image:
  repository: ghcr.io/homarr-labs/homarr
  tag: v1.42.1
  pullPolicy: Always

resources: {}

secretEncryptionKey: "e7aaba3cd6f36e5d6a7454aa05366cb484e34c8e792dd1149566f090fbed7aef"

volumes:
  appdataPath: /mnt/appdata/homarr
  enableDockerSocket: true

traefik:
  enabled: true
  domainName: homarr-k8s.nezdemkovski.cloud
  localDomainName: homarr-k8s.home.nezdemkovski.cloud
  certResolver: cloudflare
  entryPoint: websecure
  subdomain: homarr

service:
  port: 7575
