---
- name: Backup Docker Volumes
  hosts: ubuntu_servers
  become: true
  vars:
    # docker_volumes_path: "/home/{{ ansible_user }}/appdata"
    docker_volumes_path: "/mnt/data/appdata"
    zip_file_path: "/tmp/docker_volumes_backup.zip"
    local_backup_path: "~/Downloads/docker_volumes_backup.zip"
    ignored_folders:
      - "ollama"
  tasks:
    - name: Archive Docker volumes
      archive:
        path: "{{ docker_volumes_path }}"
        dest: "{{ zip_file_path }}"
        format: zip
        exclude_path: "{{ ignored_folders | map('regex_replace', '^', docker_volumes_path + '/') | list }}"
      tags: backup

    - name: Download the backup file to local machine
      fetch:
        src: "{{ zip_file_path }}"
        dest: "{{ local_backup_path }}"
        flat: yes
      tags: download

    - name: Remove the zip file from the server
      file:
        path: "{{ zip_file_path }}"
        state: absent
      tags: cleanup
