---
# Playbook: Kestra Workflow Engine Deployment
# Description: Deploys Kestra workflow orchestration engine with PostgreSQL backend
#
# This playbook handles:
# - PostgreSQL database setup for Kestra
# - Kestra server configuration with Docker socket access
# - Local storage configuration
# - Network setup for internal and Traefik communication
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - kestra_db_postgres_database: PostgreSQL database name
# - kestra_db_postgres_user: PostgreSQL username
# - kestra_db_postgres_password: PostgreSQL password
# - kestra_basic_auth_username: Email address for basic auth
# - kestra_basic_auth_password: Password for basic auth
#
# Exposed Ports:
# - 38088: Kestra UI (8080)
# - 38089: Kestra API (8081)
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/kestra.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "kestra"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"

  tasks:
    - name: Verify required variables
      assert:
        that:
          - kestra_db_postgres_database is defined
          - kestra_db_postgres_user is defined
          - kestra_db_postgres_password is defined
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Stop and remove existing containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - kestra
        - kestra-postgres
      ignore_errors: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start Kestra using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always