---
# Playbook: Cloudflare Tunnel Deployment
# Description: Deploys and configures Cloudflare Tunnel (cloudflared) for secure remote access
#
# This playbook handles:
# - Installation and configuration of Cloudflare Tunnel
# - Integration with existing Traefik network
# - Secure token management
# - Persistent configuration storage
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - ansible_become_password: Sudo password for privileged operations
# - cf_tunnel_token: Cloudflare Tunnel token from the Cloudflare Zero Trust dashboard
#
# Security Notes:
# - Tunnel token is stored securely in vault.yml
# - No ports exposed to the internet
# - Automatic tunnel management by Cloudflare
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/cloudflared.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "cloudflared"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"
    volume_base_path: "/home/{{ ansible_user }}/appdata"

  tasks:
    - name: Verify required variables
      assert:
        that:
          - cf_tunnel_token is defined and cf_tunnel_token | length > 0
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Stop and remove existing Cloudflared container if it exists
      community.docker.docker_container:
        name: cloudflared
        state: absent
      ignore_errors: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start Cloudflared using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always
