# Playbook: Ollama Deployment
# Description: Deploys Ollama for AMD GPU usage via Docker Compose
#
# This playbook handles:
# - Directory creation for the Ollama deployment
# - Docker Compose configuration generation
# - Container startup with GPU passthrough
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/ollama.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "ollama"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"

  tasks:
    - name: Verify required variables
      assert:
        that:
          - ansible_user is defined
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start Ollama stack using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always
