---
services:
  bolt-diy:
    image: ghcr.io/stackblitz-labs/bolt.diy:3be18e3
    container_name: bolt-diy
    pull_policy: always
    restart: unless-stopped
    networks:
      - traefik-proxy
    ports:
      - 5173:5173
    labels:
      - traefik.enable=true
      - traefik.http.routers.bolt-diy.rule=Host(`${SUBDOMAIN_NAME}.${DOMAIN_NAME}`) || Host(`${SUBDOMAIN_NAME}.${LOCAL_DOMAIN_NAME}`)
      - traefik.http.routers.bolt-diy.entrypoints=websecure
      - traefik.http.routers.bolt-diy.tls=true
      - traefik.http.routers.bolt-diy.tls.certresolver=cloudflare
      - traefik.http.services.bolt-diy.loadbalancer.server.port=5173
    env_file:
      - .env
networks:
  traefik-proxy:
    external: true
