---
services:
  beszel:
    image: henrygd/beszel:0.14.1
    container_name: beszel
    pull_policy: always
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`${SUBDOMAIN_NAME}.${DOMAIN_NAME}`) || Host(`${SUBDOMAIN_NAME}.${LOCAL_DOMAIN_NAME}`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=cloudflare
    ports:
      - 8090:8090
    volumes:
      - ${APPDATA_PATH}:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:0.13.2
    container_name: beszel-agent
    pull_policy: always
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      # Do not remove quotes around the key
      # KEY: 'UPDATE WITH YOUR PUBLIC KEY (copy from "Add system" dialog)'
      KEY: ${PUBLIC_KEY}
networks:
  traefik-proxy:
    external: true
