---
services:
  it-tools:
    image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    pull_policy: always
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.rule=Host(`${SUBDOMAIN_NAME}.${DOMAIN_NAME}`) || Host(`${SUBDOMAIN_NAME}.${LOCAL_DOMAIN_NAME}`)
      - traefik.http.routers.it-tools.entrypoints=websecure
      - traefik.http.routers.it-tools.tls=true
      - traefik.http.routers.it-tools.tls.certresolver=cloudflare
      - traefik.http.services.it-tools.loadbalancer.server.port=80
networks:
  traefik-proxy:
    external: true
