- hosts: all
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Get list of changed services
      set_fact:
        changed_services: "{{ lookup('env', 'CHANGED_SERVICES').split(',') }}"

    - name: Process each changed service
      include_tasks: process_service.yml
      loop: "{{ changed_services }}"
      loop_control:
        loop_var: service_name
