- hosts: all
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/targets.yml
  tasks:
    - name: Set default changed_services from environment if not defined
      set_fact:
        changed_services_raw: "{{ lookup('env', 'CHANGED_SERVICES') }}"
      when: changed_services is not defined

    - name: Convert raw string to list
      set_fact:
        changed_services_list: "{{ (changed_services_raw | default('')).split(',') }}"

    - name: Debug raw services
      debug:
        var: changed_services_raw
        verbosity: 0

    - name: Debug services list
      debug:
        var: changed_services_list
        verbosity: 0

    - name: Process each service on appropriate hosts
      include_tasks: process_service.yml
      vars:
        current_service: "{{ item }}"
        service_name: "{{ item }}"
      loop: "{{ changed_services_list }}"
      when:
        - item | trim != ""
        - deploy_targets is defined
        - inventory_hostname in (deploy_targets | dict2items | selectattr('value', 'contains', item) | map(attribute='key') | list)
