- name: Define service paths
  set_fact:
    apps_path: "/home/{{ ansible_user }}/apps/{{ current_service }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ current_service }}"
    service_name: "{{ current_service }}"

- name: Verify required variables
  assert:
    that:
      - domain_name is defined
    fail_msg: "Required variables are not defined in vault.yml"

- name: Stop old Docker Compose stack (if running)
  command: docker compose -f {{ apps_path }}/docker-compose.yml down
  ignore_errors: yes

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ apps_path }}"
    - "{{ appdata_path }}"

- name: Generate Docker Compose configuration
  template:
    src: "../docker/{{ service_name }}/docker-compose.yml"
    dest: "{{ apps_path }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Generate environment file
  template:
    src: "../docker/{{ service_name }}/.env.j2"
    dest: "{{ apps_path }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"

- name: Start Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ apps_path }}"
    files:
      - docker-compose.yml
    env_files:
      - "{{ apps_path }}/.env"
    state: present
    pull: always
    remove_orphans: true
