---
# Playbook: Authentik Identity Provider Deployment
# Description: Deploys Authentik with PostgreSQL, Redis, and Traefik integration
#
# This playbook handles:
# - Installation of Authentik server and worker
# - PostgreSQL database setup
# - Redis cache configuration
# - Traefik integration for secure HTTPS access
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - authentik_db_postgres_user: PostgreSQL username
# - authentik_db_postgres_password: PostgreSQL password
# - authentik_db_postgres_database: PostgreSQL database name
# - authentik_subdomain: Subdomain for Authentik access
# - domain_name: Primary domain
# - local_domain_name: (Optional) Local domain name
#
# Exposed Ports:
# - 9000: HTTP
# - 9443: HTTPS
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/authentik.yml

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "authentik"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"

  tasks:
    - name: Verify required Authentik variables
      assert:
        that:
          - authentik_db_postgres_user is defined
          - authentik_db_postgres_password is defined
          - authentik_db_postgres_database is defined
          - authentik_subdomain is defined
          - domain_name is defined
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Create required Authentik directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Stop and remove existing Authentik containers if they exist
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - authentik-postgres
        - authentik-redis
        - authentik-server
        - authentik-worker
        - authentik-outpost
      ignore_errors: yes

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start Authentik using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always