---
# Playbook: Portainer CE Deployment
# Description: Deploys and configures Portainer Community Edition with Traefik integration
#
# This playbook handles:
# - Installation and configuration of Portainer CE
# - Traefik integration for secure HTTPS access
# - Docker socket mounting for container management
# - Persistent volume setup for Portainer data
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - ansible_become_password: Sudo password for privileged operations
# - portainer_subdomain: Subdomain for Portainer access
# - domain_name: Primary domain for the infrastructure
#
# Exposed Ports:
# - 30011: HTTP UI (mapped from 9000)
# - 9443: HTTPS UI
# - 8010: Edge agent API
#
# Security Notes:
# - Traefik handles SSL termination
# - Docker socket is mounted read-only for security
# - All web traffic is encrypted via HTTPS
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/portainer.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "portainer"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"
    volume_base_path: "/home/{{ ansible_user }}/appdata"

  tasks:
    - name: Verify required variables
      assert:
        that:
          - portainer_subdomain is defined
          - domain_name is defined
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Stop and remove existing Portainer container if it exists
      community.docker.docker_container:
        name: portainer
        state: absent
      ignore_errors: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Verify docker socket exists and is accessible
      stat:
        path: /var/run/docker.sock
      register: docker_sock

    - name: Fail if docker socket is not accessible
      fail:
        msg: "Docker socket is not accessible at /var/run/docker.sock"
      when: not docker_sock.stat.exists

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml.j2"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Start Portainer using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        state: present
        pull: always
