---
# Playbook: Uptime Kuma Deployment
# Description: Deploys and configures Uptime Kuma monitoring tool with Traefik integration
#
# This playbook handles:
# - Installation and configuration of Uptime Kuma
# - Traefik integration for secure HTTPS access
# - Persistent volume setup for monitoring data
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - ansible_become_password: Sudo password for privileged operations
# - domain_name: Primary domain for the infrastructure
# - local_domain_name: Internal domain name (optional)
# - uptime_kuma_subdomain: Subdomain for Uptime Kuma access (e.g., 'status')
#
# Exposed Ports:
# - 30015: HTTP UI (mapped from 3001)
#
# Security Notes:
# - Traefik handles SSL termination
# - All web traffic is encrypted via HTTPS
# - Data persistence through Docker volumes
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/uptime-kuma.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "uptime-kuma"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"
    volume_base_path: "/home/{{ ansible_user }}/appdata"

  tasks:
    - name: Verify required variables
      assert:
        that:
          - domain_name is defined
          - uptime_kuma_subdomain is defined
        fail_msg: "Required variables are not defined. Please ensure domain_name and uptime_kuma_subdomain are set in vault.yml"

    - name: Stop and remove existing Uptime Kuma container if it exists
      community.docker.docker_container:
        name: uptime-kuma
        state: absent
      ignore_errors: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml.j2"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Start Uptime Kuma using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        state: present
        pull: always
