---
# Playbook: Open WebUI Deployment
# Description: Deploys and configures Open WebUI for Ollama with Traefik integration
#
# This playbook handles:
# - Installation and configuration of Open WebUI
# - Integration with Ollama via host.docker.internal
# - Traefik integration for secure HTTPS access
# - Persistent volume setup for WebUI data
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - ansible_become_password: Sudo password for privileged operations
# - domain_name: Primary domain for the infrastructure
# - local_domain_name: Internal domain name (optional)
# - open_webui_subdomain: Subdomain for Open WebUI access
#
# Dependencies:
# - Requires Ollama to be running on port 11434
# - Requires Traefik to be configured and running
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/open-webui.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "open-webui"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"
    volume_base_path: "/home/{{ ansible_user }}/appdata"

  tasks:
    - name: Verify required variables
      assert:
        that:
          - domain_name is defined
          - open_webui_subdomain is defined
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Stop and remove existing Open WebUI container if it exists
      community.docker.docker_container:
        name: open-webui
        state: absent
      ignore_errors: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start Open WebUI using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always
