---
# Playbook: Watchtower Deployment
# Description: Deploys and configures Watchtower for automatic container updates
#
# This playbook handles:
# - Installation and configuration of Watchtower
# - Integration with Docker socket
# - Secure and persistent configuration
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - ansible_become_password: Sudo password for privileged operations
#
# Security Notes:
# - Docker socket is mounted for container management
# - Automatic container updates managed by Watchtower
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/watchtower.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "watchtower"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"

  tasks:
    - name: Stop and remove existing Watchtower container if it exists
      community.docker.docker_container:
        name: watchtower
        state: absent
      ignore_errors: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      loop:
        - "{{ apps_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start Watchtower using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always
