# Playbook: IT-Tools Deployment
# Description: Deploys the IT-Tools
#
# This playbook handles:
# - Docker Compose configuration for IT-Tools
# - Traefik integration for secure HTTPS access
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - domain_name: Primary domain for Traefik
# - it_tools_subdomain: Subdomain for IT-Tools
#
# Exposed Ports:
# - 8080: IT-Tools Web UI
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/it-tools.yml --vault-password-file password.txt

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "it-tools"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"

  tasks:
    - name: Verify required variables
      assert:
        that:
          - domain_name is defined
          - it_tools_subdomain is defined
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0750"
      loop:
        - "{{ apps_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0640"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start IT-Tools stack using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always
