---
# Playbook: Abiotic Factor Game Server Deployment
# Description: Deploys Abiotic Factor game server with Docker and Traefik integration
#
# Required Variables (defined in vault.yml):
# - ansible_user: SSH user for remote access
# - domain_name: Primary domain for the infrastructure
# - local_domain_name: Internal domain name (optional)
# - abiotic_server_name: Name of the game server
# - abiotic_server_password: Server password (optional)
#
# Exposed Ports (internal):
# - 2456/udp: Primary game port
# - 2457/udp: Secondary port
# - 2458/udp: Backup port
#
# Usage:
# ansible-playbook -i inventory/hosts.yml playbooks/abiotic-factor.yml

- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  vars:
    service_name: "abiotic-factor"
    apps_path: "/home/{{ ansible_user }}/apps/{{ service_name }}"
    appdata_path: "/home/{{ ansible_user }}/appdata/{{ service_name }}"

  tasks:
    - name: Verify required variables
      assert:
        that:
          # - domain_name is defined
          # - abiotic_server_name is defined
        fail_msg: "Required variables are not defined in vault.yml"

    - name: Stop and remove existing Abiotic Factor container if it exists
      community.docker.docker_container:
        name: abiotic-factor
        state: absent
      ignore_errors: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      loop:
        - "{{ apps_path }}"
        - "{{ appdata_path }}"

    - name: Generate Docker Compose configuration
      template:
        src: "../files/{{ service_name }}/docker-compose.yml"
        dest: "{{ apps_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Generate environment file
      template:
        src: "../files/{{ service_name }}/.env.j2"
        dest: "{{ apps_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Start Abiotic Factor server using Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ apps_path }}"
        files:
          - docker-compose.yml
        env_files:
          - "{{ apps_path }}/.env"
        state: present
        pull: always
