---
- hosts: ubuntu_servers
  become: true
  vars_files:
    - ../group_vars/ubuntu_servers/vault.yml
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Upgrade all apt packages
      apt:
        upgrade: dist

    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present

    - name: Start and enable qemu-guest-agent
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started

    - name: Install basic utilities
      apt:
        name:
          - curl
          - vim
          - git
          - ufw
        state: present

    - name: Remove old versions of Docker
      apt:
        name:
          - docker
          - docker.io
          - containerd
        state: absent

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update apt package list after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker Engine and Docker Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Create Docker network for Traefik
      docker_network:
        name: traefik-proxy
        driver: bridge
        state: present

    - name: Add user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
