---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16
    container_name: uptime-kuma
    pull_policy: always
    restart: unless-stopped
    # ports:
    #   - 3001:3001
    networks:
      - traefik-proxy
    volumes:
      - ${APPDATA_PATH}:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`${SUBDOMAIN_NAME}.${DOMAIN_NAME}`) || Host(`${SUBDOMAIN_NAME}.${LOCAL_DOMAIN_NAME}`)
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=cloudflare
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
networks:
  traefik-proxy:
    external: true
