---
services:
  traefik:
    image: traefik:v3.3.4
    container_name: traefik
    pull_policy: always
    restart: always
    networks:
      - traefik-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ${APPDATA_PATH}/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${APPDATA_PATH}/conf.d/:/etc/traefik/conf.d/:ro
      - ${APPDATA_PATH}/data/certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
networks:
  traefik-proxy:
    external: true