apiVersion: v1
kind: Service
metadata:
  name: {{ include "homarr.fullname" . }}
spec:
  selector:
    app: {{ include "homarr.name" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
